### ISSUE TITLE
给您点赞！

### ISSUE THREAD

**Issue by ihanwen99** [gcyml/leetcode-crawler#1]
**您的这个项目特别的好，感激，特地过来给您 Star ！**

我之前准备Leetcode-CN题目的时候，是基于Hexo生成模板，手动的复制粘贴题目，记录心得和Code。

我今天初步尝试了一下，发现英文版能够爬取到最新的题目，迁移到中文版暂时还没有完全研究明白。

我测试了一下中文版的 `面试题` 部分有着不同的设计 [FrontedId]，略微修改一下，可以生成和英文版同样数目的题目。

```python
def generate_question_markdown(self, question, path, has_get_code): 
        if isinstance(question['frontedId'],int):   
```

我的需求和尝试也很简答，我会继续研究的！**感觉您的Code也很漂亮，优秀！**

我之前已经记录了快300道题目的题解，感觉未来搬迁过来还有点难度哈哈！

**Comment by ihanwen99** [comment]
也想问问您，您最近有没有开发中文版爬虫的想法呢？感谢感谢！

**Comment by gcyml** [comment]
感谢，因为不怎么用中文版的，所以没有去做，这段时间有空会更新下支持
